CC = g++

server: adam_network_main_map_test.cpp
	${CC} adam_network_main_map_test.cpp -o server -lSDL2
	
client: adam_network_map_test_client.cpp
	${CC} adam_network_map_test_client.cpp -o client -lSDL2

